package bg.sofia.uni.fmi.mjt.authserver.command;

import bg.sofia.uni.fmi.mjt.authserver.UserManager;
import bg.sofia.uni.fmi.mjt.authserver.response.Response;

public interface Command {
    /**
     * Executes the command.
     *
     * @param userManager resources for the command.
     * @return The response generated by the command.
     * @throws RuntimeException If an IO error occurs during command execution.
     */
    Response execute(UserManager userManager);
}
